### ISSUE TITLE
Curly braces are not recognized by react-latex

### ISSUE THREAD

**Issue by cavaunpeu** [zzish/react-latex#2]
Inside of a React component, React treats curly braces as per normal.

> How do I achieve a grouped super/sub script? e.g. R_{u,i}

**Comment by martijnvandijke** [comment]
Can confirm this bug, any work arounds ?

**Comment by blaiprat** [comment]
Hi, this might be because in our projects and for legacy purposes, we use the curly brackets to separate normal text and latex. 

I'll try to move this functionality out of the module so expressions like `R_{u,i}`can work as expected

**Comment by blaiprat** [comment]
Quick update and the current version works fine. Are you wrapping your LaTeX syntax around dollar signs, like this: `$R_{u,i}$`

**Comment by talyssonoc** [comment]
@cavaunpeu @martijnvandijke react-katex has a way to solve this problem, you can check it here: https://github.com/talyssonoc/react-katex/issues/6

It happens because React interpret content between curly braces as JavaScript values.

**Comment by vic317yeh** [comment]
This problem is still not solved. React component does not recognize BlockMath. Can someone look into the issue? Ex. $P_{'{data}'}$ is not working, even though the curly braces are escaped. Thank you!

**Comment by talyssonoc** [comment]
@vic317yeh can you show me the full code you're trying to render with BlockMath?

**Comment by perkss** [comment]
@talyssonoc is this BlockMath available in react-latex or react-katex only? When importing I have been doing this: import Latex from 'react-latex'; but when trying block math getting issues. Can you share example of the import?

**Comment by talyssonoc** [comment]
I'm not sure how to do that in `react-latex`, but in `react-katex` you can do that:

```jsx
import { BlockMath } from 'react-katex';

// ...

<BlockMath math="a^m \\times a^n = a^{m+n}" /> // don't forget to escape the `\` :)
```

**Comment by perkss** [comment]
Thanks @talyssonoc I have tried that and get the error `Uncaught TypeError: Cannot read property 'string' of undefined
    at Object.<anonymous> (bundle.js:65414)
    at __webpack_require__ (bundle.js:65334)
    at Object.<anonymous> (bundle.js:65367)
    at __webpack_require__ (bundle.js:65334)
    at bundle.js:65354
    at bundle.js:65357
    at webpackUniversalModuleDefinition (bundle.js:65307)
    at Object.<anonymous> (bundle.js:65314)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value`

Along with warnings when building: 

`npm install --save react-katex
npm WARN react-katex@1.2.0 requires a peer of katex@^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-katex@1.2.0 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-latex@1.0.1 requires a peer of react@^15.3.0 but none is installed. You must install peer dependencies yourself.`

In package.json I do have
`"katex": "^0.9.0-beta","react": "^16.2.0",  "react-katex": "^1.2.0",`

So it seems a bit odd this maybe is the newer version of React supported?

**Comment by perkss** [comment]
So removing the warnings has worked so setting the values to:
  "react-katex": "1.2.0",
 "katex": "^0.7.0",
  "react": "15.3.2",

So seems like the library does not currently work with newer versions of REACT.

**Comment by blaiprat** [comment]
Seems like the  issue is related to our good neighbour "react-katex", closing this issue
