### ISSUE TITLE
dangerouslySetInnerHTML vulnerability?

### ISSUE THREAD

**Issue by sjosund** [zzish/react-latex#26]
Hi, 
I'm quite new to FE-development and have a security question:
Is it a possible vulnerability that dangerouslySetInnerHTML is being used [here](https://github.com/zzish/react-latex/blob/c550badca6bf4d57d02655b70085159d5cbb86bd/src/latex.js#L66), in the case of accepting user input?
Thanks for your help!

**Comment by blaiprat** [comment]
In short, the implementation of  `dangerouslySetInnerHTML` is secure and no user input can cause harm when passed straight to the Latex component. 

As you mention, the component is indeed calling `dangerouslySetInnerHTML`, but only with the value we get after calling `katex.renderToString()`. Any user input submitted will only be interpreted as a string or a valid latex entity.

If a user tries to enter HTML, you'll see that the whole HTML snippet is rendered as a string on the page, so no need to worry about user generated input.   To give you a better idea on how it will work, try entering some HTML on the KaTeX Demo page: https://katex.org/#demo

**Comment by sjosund** [comment]
Great, thanks for the explanation.
